print("The first atomic bomb was dropped on Hiroshima on August 6, 1945.")
input()
print("This caused hundreds of thousands of deaths and caused great panic in Japan.")
input()
print("This is very tragic, countless people died in agony.")
input()
print("But the Empire of Japan was determined not to surrender and was ready to fight the United States to the end")
input()
print("In order to end the war as soon as possible, the United States dropped a second atomic bomb on Nagasaki.")
input()
print("The explosion killed at least 74,000 people.")
input()
print("This dealt a heavy blow to the Japanese army and the people.")
input()
print("The Japanese government saw that the situation was already decided, and in order to leave a glimmer of hope for survival, it finally surrendered unconditionally on September 2, 1945.")
input()
print("World War II ended")
input()
print("Afterwards, Japan's economy withered, food was in short supply, and celebrities were in panic.")
input()
print("It took decades to return to normal.")
input()
print("It can be seen that the impact of war on society is huge.")

print("So you returned home, and Japan was not hit by the atomic bomb.")
input()
print("The president was angry, but there was nothing he could do.")
input()
print("After discussion, in order to end the war as soon as possible, the United States finally chose to land in Japan and conduct a ground war.")
input()
print("However, Japan still believed that it had the strength to fight and continued to choose to fight.")
input()
print("The United States launched a large-scale battle after landing, and all the Japanese soldiers they saw were killed")
input()
print("The United States soon reached the vicinity of Tokyo.")
input()
print("Obviously, Japan overestimated its own strength")
input()
print("But they still refused to surrender and were ready to fight to the end")
input()
print("In the end, no amount of resistance could cover up the gap in power, and the United States killed the emperor and took Tokyo.")
input()
print("Japan suffered heavy casualties and finally announced its surrender")
input()
print("At this point, World War II finally came to an end")
input()
print("")
input()
