print("The first atomic bomb was dropped on Hiroshima on August 6, 1945.")
input()
print("This caused hundreds of thousands of deaths and caused great panic in Japan.")
input()
print("This is very tragic, countless people died in agony.")
input()
print("But the Empire of Japan was determined not to surrender and was ready to fight the United States to the end")
input()
print("In order to end the war as soon as possible, the United States dropped a second atomic bomb on Nagasaki.")
input()
print("The explosion killed at least 74,000 people.")
input()
print("This dealt a heavy blow to the Japanese army and the people.")
input()
print("The Japanese government saw that the situation was already decided, and in order to leave a glimmer of hope for survival, it finally surrendered unconditionally on September 2, 1945.")
input()
print("World War II ended")
input()
print("Afterwards, Japan's economy withered, food was in short supply, and celebrities were in panic.")
input()
print("It took decades to return to normal.")
input()
print("It can be seen that the impact of war on society is huge.")
input()
print("")
print("")
